注釈的なの追加
shinjuku-lt/shinjuku-lt-website pull request #32
Opened 2017-11-18 06:48 UTC by kyusuke7

kptの内容反映

以下の説明を追加

* 発表内容はLT(5分)に縛らない
* なんでも発表していいよ
* 誰を呼んでもいいよ

2017-11-18 08:53 UTC, HomMarkHunt requested changes
Slide.vueではなくAboutUs.vue移動した方がいいかなーとオマス！

2017-11-18 08:53 UTC, HomMarkHunt commented on src/components/Contact.vue
> +        P Shinjuku.LTに誘いたい！と思った人をどんどん誘いましょう。
ここはちょっと文章の意味がよくわからないですね！
> 参加される方へ -> 誘いましょう！

```html
h2 参加条件
  P 参加条件はないですのでふごふごペラペラ
```
みたいな方がわかりやすいかなと思いました

2017-11-18 08:53 UTC, HomMarkHunt commented on src/components/Slides.vue
> +              | 聞いて欲しい話、ためになった話などがあれば、どんどん発表していきましょう！
文章自体はとてもいいと思うのですが、すでに参加しているメンバーへのメッセージになってるのが気になりました。

> 発表していきましょう！
> 話したい内容に全力を注いでください

他は全て未参加の人向けに書いてあるので、対象を合わせてもらえればと思います！

2017-12-01 08:01 UTC, HomMarkHunt commented
よきおとおもいます。
![LGTM](http://www.lgtm.in/p/MA0eZppRp)

2017-12-01 08:01 UTC, HomMarkHunt approved these changes

2017-12-01 08:02 UTC, sgswtky commented
マージするぞ

2017-12-01 08:02 UTC, merged